name: Build
on:
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
  BINARYEN_VERSION: version_104
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: download binaryen
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "WebAssembly/binaryen"
          version: "tags/${{ env.BINARYEN_VERSION }}"
          file: "binaryen-${{ env.BINARYEN_VERSION }}-x86_64-linux.tar.gz"
          target: "binaryen.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup binaryen
        run: |
          tar -xvf binaryen.tar.gz
          sudo cp ./binaryen-${{ env.BINARYEN_VERSION }}/bin/wasm-opt /usr/local/bin
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - name: install cargo make
        uses: baptiste0928/cargo-install@v1.0.0
        with:
          crate: cargo-make
          version: latest
      - name: install wasm-snip
        uses: baptiste0928/cargo-install@v1.0.0
        with:
          crate: wasm-snip
          version: latest
      - name: Build
        run: cargo make w4-bundle
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}